/**
 * Copyright (c) 2013-2022, Alibaba Group Holding Limited;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * </p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.aliyun.polardbx.binlog.domain.po;

public class TablesExtWithBLOBs extends TablesExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tables_ext.db_meta_map
     */
    private String dbMetaMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tables_ext.tb_meta_map
     */
    private String tbMetaMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tables_ext.ext_partitions
     */
    private String extPartitions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tables_ext.db_meta_map
     *
     * @return the value of tables_ext.db_meta_map
     */
    public String getDbMetaMap() {
        return dbMetaMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tables_ext.db_meta_map
     *
     * @param dbMetaMap the value for tables_ext.db_meta_map
     */
    public void setDbMetaMap(String dbMetaMap) {
        this.dbMetaMap = dbMetaMap == null ? null : dbMetaMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tables_ext.tb_meta_map
     *
     * @return the value of tables_ext.tb_meta_map
     */
    public String getTbMetaMap() {
        return tbMetaMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tables_ext.tb_meta_map
     *
     * @param tbMetaMap the value for tables_ext.tb_meta_map
     */
    public void setTbMetaMap(String tbMetaMap) {
        this.tbMetaMap = tbMetaMap == null ? null : tbMetaMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tables_ext.ext_partitions
     *
     * @return the value of tables_ext.ext_partitions
     */
    public String getExtPartitions() {
        return extPartitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tables_ext.ext_partitions
     *
     * @param extPartitions the value for tables_ext.ext_partitions
     */
    public void setExtPartitions(String extPartitions) {
        this.extPartitions = extPartitions == null ? null : extPartitions.trim();
    }
}