// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TxnStream.proto

package com.aliyun.polardbx.binlog.protocol;

public interface DumpReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aliyun.polardbx.binlog.protocol.DumpReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnMessage txnMessage = 1;</code>
   */
  java.util.List<com.aliyun.polardbx.binlog.protocol.TxnMessage> 
      getTxnMessageList();
  /**
   * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnMessage txnMessage = 1;</code>
   */
  com.aliyun.polardbx.binlog.protocol.TxnMessage getTxnMessage(int index);
  /**
   * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnMessage txnMessage = 1;</code>
   */
  int getTxnMessageCount();
  /**
   * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnMessage txnMessage = 1;</code>
   */
  java.util.List<? extends com.aliyun.polardbx.binlog.protocol.TxnMessageOrBuilder> 
      getTxnMessageOrBuilderList();
  /**
   * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnMessage txnMessage = 1;</code>
   */
  com.aliyun.polardbx.binlog.protocol.TxnMessageOrBuilder getTxnMessageOrBuilder(
      int index);
}
