/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 *
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TxnStream.proto

package com.aliyun.polardbx.binlog.protocol;

/**
 * Protobuf enum {@code com.aliyun.polardbx.binlog.protocol.PacketMode}
 */
public enum PacketMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   **
   *高阶对象
   * </pre>
   *
   * <code>OBJECT = 0;</code>
   */
  OBJECT(0),
  /**
   * <pre>
   **
   *低阶数组
   * </pre>
   *
   * <code>BYTES = 1;</code>
   */
  BYTES(1),
  /**
   * <pre>
   **
   *随机，测试用
   * </pre>
   *
   * <code>RANDOM = 2;</code>
   */
  RANDOM(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   **
   *高阶对象
   * </pre>
   *
   * <code>OBJECT = 0;</code>
   */
  public static final int OBJECT_VALUE = 0;
  /**
   * <pre>
   **
   *低阶数组
   * </pre>
   *
   * <code>BYTES = 1;</code>
   */
  public static final int BYTES_VALUE = 1;
  /**
   * <pre>
   **
   *随机，测试用
   * </pre>
   *
   * <code>RANDOM = 2;</code>
   */
  public static final int RANDOM_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PacketMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PacketMode forNumber(int value) {
    switch (value) {
      case 0: return OBJECT;
      case 1: return BYTES;
      case 2: return RANDOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PacketMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PacketMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PacketMode>() {
          public PacketMode findValueByNumber(int number) {
            return PacketMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.aliyun.polardbx.binlog.protocol.TxnStream.getDescriptor().getEnumTypes().get(0);
  }

  private static final PacketMode[] VALUES = values();

  public static PacketMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PacketMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.aliyun.polardbx.binlog.protocol.PacketMode)
}

