/*
 *
 * Copyright (c) 2013-2021, Alibaba Group Holding Limited;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TxnStream.proto

package com.aliyun.polardbx.binlog.protocol;

public interface TxnDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aliyun.polardbx.binlog.protocol.TxnData)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnItem txnItems = 1;</code>
     */
    java.util.List<com.aliyun.polardbx.binlog.protocol.TxnItem>
    getTxnItemsList();

    /**
     * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnItem txnItems = 1;</code>
     */
    com.aliyun.polardbx.binlog.protocol.TxnItem getTxnItems(int index);

    /**
     * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnItem txnItems = 1;</code>
     */
    int getTxnItemsCount();

    /**
     * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnItem txnItems = 1;</code>
     */
    java.util.List<? extends com.aliyun.polardbx.binlog.protocol.TxnItemOrBuilder>
    getTxnItemsOrBuilderList();

    /**
     * <code>repeated .com.aliyun.polardbx.binlog.protocol.TxnItem txnItems = 1;</code>
     */
    com.aliyun.polardbx.binlog.protocol.TxnItemOrBuilder getTxnItemsOrBuilder(
        int index);
}
