/**
 * Copyright (c) 2013-2022, Alibaba Group Holding Limited;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * </p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetaData.proto

package com.aliyun.polardbx.meta;

public final class MetaData {
  private MetaData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aliyun_polardbx_meta_SchemaObjectEntity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aliyun_polardbx_meta_SchemaObjectEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MetaData.proto\022\030com.aliyun.polardbx.me" +
      "ta\"A\n\022SchemaObjectEntity\022\014\n\004name\030\001 \001(\t\022\014" +
      "\n\004type\030\002 \001(\t\022\017\n\007stmtSql\030\003 \001(\tB\036\n\030com.ali" +
      "yun.polardbx.metaH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_aliyun_polardbx_meta_SchemaObjectEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aliyun_polardbx_meta_SchemaObjectEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aliyun_polardbx_meta_SchemaObjectEntity_descriptor,
        new java.lang.String[] { "Name", "Type", "StmtSql", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
