/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 *
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MetaData.proto

package com.aliyun.polardbx.meta;

public interface SchemaObjectEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aliyun.polardbx.meta.SchemaObjectEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string stmtSql = 3;</code>
   * @return The stmtSql.
   */
  java.lang.String getStmtSql();
  /**
   * <code>string stmtSql = 3;</code>
   * @return The bytes for stmtSql.
   */
  com.google.protobuf.ByteString
      getStmtSqlBytes();
}
