/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 * <p>
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.aliyun.polardbx.rpc.cdc;

public final class DumperServer {
  private DumperServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowBinlogEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowBinlogEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_DumpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_DumpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowBinlogDumpStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowBinlogDumpStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_BinaryLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_BinaryLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_FullBinaryLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_FullBinaryLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_MasterStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_MasterStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_FullMasterStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_FullMasterStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_BinlogEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_BinlogEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_DumpStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_DumpStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_RplCommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_RplCommandResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ChangeMasterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ChangeMasterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_StartSlaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_StartSlaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_StopSlaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_StopSlaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ResetSlaveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ResetSlaveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ChangeReplicationFilterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ChangeReplicationFilterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowSlaveStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowSlaveStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_ShowSlaveStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_ShowSlaveStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_BinlogDumpStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_BinlogDumpStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dumper_GetDumperInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dumper_GetDumperInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DumperServer.proto\022\006dumper\"F\n\007Request\022" +
      "\013\n\003req\030\001 \001(\t\022\022\n\nstreamName\030\002 \001(\t\022\032\n\022excl" +
      "udeRemoteFiles\030\003 \001(\010\"m\n\027ShowBinlogEvents" +
      "Request\022\017\n\007logName\030\001 \001(\t\022\013\n\003pos\030\002 \001(\003\022\016\n" +
      "\006offset\030\003 \001(\003\022\020\n\010rowCount\030\004 \001(\003\022\022\n\nstrea" +
      "mName\030\005 \001(\t\"\221\001\n\013DumpRequest\022\020\n\010fileName\030" +
      "\001 \001(\t\022\020\n\010position\030\002 \001(\003\022)\n\tsplitMode\030\003 \001" +
      "(\0162\026.dumper.EventSplitMode\022\022\n\nregistered" +
      "\030\004 \001(\010\022\013\n\003ext\030\005 \001(\t\022\022\n\nstreamName\030\006 \001(\t\"" +
      "1\n\033ShowBinlogDumpStatusRequest\022\022\n\nstream" +
      "Name\030\001 \001(\t\".\n\tBinaryLog\022\017\n\007logName\030\001 \001(\t" +
      "\022\020\n\010fileSize\030\002 \001(\003\"\330\001\n\rFullBinaryLog\022\017\n\007" +
      "logName\030\001 \001(\t\022\020\n\010fileSize\030\002 \001(\003\022\023\n\013creat" +
      "edTime\030\003 \001(\t\022\026\n\016lastModifyTime\030\004 \001(\t\022\026\n\016" +
      "firstEventTime\030\005 \001(\t\022\025\n\rlastEventTime\030\006 " +
      "\001(\t\022\017\n\007lastTso\030\007 \001(\t\022\024\n\014uploadStatus\030\010 \001" +
      "(\t\022\024\n\014fileLocation\030\t \001(\t\022\013\n\003ext\030\n \001(\t\"s\n" +
      "\014MasterStatus\022\014\n\004file\030\001 \001(\t\022\020\n\010position\030" +
      "\002 \001(\003\022\022\n\nbinlogDoDB\030\003 \001(\t\022\026\n\016binlogIgnor" +
      "eDB\030\004 \001(\t\022\027\n\017executedGtidSet\030\005 \001(\t\"\366\001\n\020F" +
      "ullMasterStatus\022\014\n\004file\030\001 \001(\t\022\020\n\010positio" +
      "n\030\002 \001(\003\022\017\n\007lastTso\030\003 \001(\t\022\021\n\tdelayTime\030\004 " +
      "\001(\003\022\021\n\tavgRevEps\030\005 \001(\003\022\021\n\tavgRevBps\030\006 \001(" +
      "\003\022\023\n\013avgWriteEps\030\007 \001(\003\022\023\n\013avgWriteBps\030\010 " +
      "\001(\003\022\023\n\013avgWriteTps\030\t \001(\003\022\024\n\014avgUploadBps" +
      "\030\n \001(\003\022\022\n\navgDumpBps\030\013 \001(\003\022\017\n\007extInfo\030\014 " +
      "\001(\t\"q\n\013BinlogEvent\022\017\n\007logName\030\001 \001(\t\022\013\n\003p" +
      "os\030\002 \001(\003\022\021\n\teventType\030\003 \001(\t\022\020\n\010serverId\030" +
      "\004 \001(\003\022\021\n\tendLogPos\030\005 \001(\003\022\014\n\004info\030\006 \001(\t\"2" +
      "\n\nDumpStream\022\017\n\007payload\030\001 \001(\014\022\023\n\013isHeart" +
      "Beat\030\002 \001(\010\"7\n\022RplCommandResponse\022\022\n\nresu" +
      "ltCode\030\001 \001(\005\022\r\n\005error\030\002 \001(\t\"&\n\023ChangeMas" +
      "terRequest\022\017\n\007request\030\001 \001(\t\"$\n\021StartSlav" +
      "eRequest\022\017\n\007request\030\001 \001(\t\"#\n\020StopSlaveRe" +
      "quest\022\017\n\007request\030\001 \001(\t\"$\n\021ResetSlaveRequ" +
      "est\022\017\n\007request\030\001 \001(\t\"1\n\036ChangeReplicatio" +
      "nFilterRequest\022\017\n\007request\030\001 \001(\t\")\n\026ShowS" +
      "laveStatusRequest\022\017\n\007request\030\001 \001(\t\"+\n\027Sh" +
      "owSlaveStatusResponse\022\020\n\010response\030\001 \001(\t\"" +
          "\271\001\n\020BinlogDumpStatus\022\n\n\002ip\030\001 \001(\t\022\n\n\002id\030\002" +
          " \001(\003\022\017\n\007traceId\030\003 \001(\t\022\014\n\004port\030\004 \001(\005\022\020\n\010f" +
          "ileName\030\005 \001(\t\022\020\n\010position\030\006 \001(\003\022\r\n\005delay" +
          "\030\007 \001(\003\022\013\n\003bps\030\010 \001(\003\022\031\n\021lastSyncTimeStamp" +
          "\030\t \001(\003\022\023\n\013aliveSecond\030\n \001(\003\"\241\001\n\025GetDumpe" +
          "rInfoResponse\022\014\n\004file\030\001 \001(\t\022\020\n\010position\030" +
          "\002 \001(\003\022\032\n\022lastEventTimestamp\030\003 \001(\003\022\r\n\005del" +
          "ay\030\004 \001(\003\022\024\n\014sessionCount\030\005 \001(\005\022\025\n\ravgDum" +
          "pBpsSum\030\006 \001(\003\022\020\n\010cpuUsage\030\007 \001(\001*4\n\016Event" +
          "SplitMode\022\n\n\006SERVER\020\000\022\n\n\006CLIENT\020\001\022\n\n\006RAN" +
          "DOM\020\0022\313\010\n\nCdcService\0228\n\016ShowBinaryLogs\022\017" +
          ".dumper.Request\032\021.dumper.BinaryLog\"\0000\001\022@" +
          "\n\022ShowFullBinaryLogs\022\017.dumper.Request\032\025." +
          "dumper.FullBinaryLog\"\0000\001\022;\n\020ShowMasterSt" +
          "atus\022\017.dumper.Request\032\024.dumper.MasterSta" +
          "tus\"\000\022C\n\024ShowFullMasterStatus\022\017.dumper.R" +
          "equest\032\030.dumper.FullMasterStatus\"\000\022L\n\020Sh" +
          "owBinlogEvents\022\037.dumper.ShowBinlogEvents" +
          "Request\032\023.dumper.BinlogEvent\"\0000\001\0223\n\004Dump" +
          "\022\023.dumper.DumpRequest\032\022.dumper.DumpStrea" +
          "m\"\0000\001\0223\n\004Sync\022\023.dumper.DumpRequest\032\022.dum" +
          "per.DumpStream\"\0000\001\022I\n\014ChangeMaster\022\033.dum" +
          "per.ChangeMasterRequest\032\032.dumper.RplComm" +
          "andResponse\"\000\022_\n\027ChangeReplicationFilter" +
          "\022&.dumper.ChangeReplicationFilterRequest" +
          "\032\032.dumper.RplCommandResponse\"\000\022E\n\nStartS" +
          "lave\022\031.dumper.StartSlaveRequest\032\032.dumper" +
          ".RplCommandResponse\"\000\022C\n\tStopSlave\022\030.dum" +
          "per.StopSlaveRequest\032\032.dumper.RplCommand" +
          "Response\"\000\022E\n\nResetSlave\022\031.dumper.ResetS" +
          "laveRequest\032\032.dumper.RplCommandResponse\"" +
          "\000\022V\n\017ShowSlaveStatus\022\036.dumper.ShowSlaveS" +
          "tatusRequest\032\037.dumper.ShowSlaveStatusRes" +
          "ponse\"\0000\001\022Y\n\024ShowBinlogDumpStatus\022#.dump" +
          "er.ShowBinlogDumpStatusRequest\032\030.dumper." +
          "BinlogDumpStatus\"\0000\001\022U\n\rgetDumperInfo\022#." +
          "dumper.ShowBinlogDumpStatusRequest\032\035.dum" +
          "per.GetDumperInfoResponse\"\000B!\n\033com.aliyu" +
          "n.polardbx.rpc.cdcH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dumper_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dumper_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_Request_descriptor,
        new java.lang.String[] { "Req", "StreamName", "ExcludeRemoteFiles", });
    internal_static_dumper_ShowBinlogEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dumper_ShowBinlogEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowBinlogEventsRequest_descriptor,
        new java.lang.String[] { "LogName", "Pos", "Offset", "RowCount", "StreamName", });
    internal_static_dumper_DumpRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dumper_DumpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_DumpRequest_descriptor,
        new java.lang.String[] { "FileName", "Position", "SplitMode", "Registered", "Ext", "StreamName", });
    internal_static_dumper_ShowBinlogDumpStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dumper_ShowBinlogDumpStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowBinlogDumpStatusRequest_descriptor,
        new java.lang.String[] { "StreamName", });
    internal_static_dumper_BinaryLog_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_dumper_BinaryLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_BinaryLog_descriptor,
        new java.lang.String[] { "LogName", "FileSize", });
    internal_static_dumper_FullBinaryLog_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_dumper_FullBinaryLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_FullBinaryLog_descriptor,
        new java.lang.String[] { "LogName", "FileSize", "CreatedTime", "LastModifyTime", "FirstEventTime", "LastEventTime", "LastTso", "UploadStatus", "FileLocation", "Ext", });
    internal_static_dumper_MasterStatus_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_dumper_MasterStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_MasterStatus_descriptor,
        new java.lang.String[] { "File", "Position", "BinlogDoDB", "BinlogIgnoreDB", "ExecutedGtidSet", });
    internal_static_dumper_FullMasterStatus_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_dumper_FullMasterStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_FullMasterStatus_descriptor,
        new java.lang.String[] { "File", "Position", "LastTso", "DelayTime", "AvgRevEps", "AvgRevBps", "AvgWriteEps", "AvgWriteBps", "AvgWriteTps", "AvgUploadBps", "AvgDumpBps", "ExtInfo", });
    internal_static_dumper_BinlogEvent_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_dumper_BinlogEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_BinlogEvent_descriptor,
        new java.lang.String[] { "LogName", "Pos", "EventType", "ServerId", "EndLogPos", "Info", });
    internal_static_dumper_DumpStream_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_dumper_DumpStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_DumpStream_descriptor,
        new java.lang.String[] { "Payload", "IsHeartBeat", });
    internal_static_dumper_RplCommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_dumper_RplCommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_RplCommandResponse_descriptor,
        new java.lang.String[] { "ResultCode", "Error", });
    internal_static_dumper_ChangeMasterRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_dumper_ChangeMasterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ChangeMasterRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_StartSlaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_dumper_StartSlaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_StartSlaveRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_StopSlaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_dumper_StopSlaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_StopSlaveRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ResetSlaveRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_dumper_ResetSlaveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ResetSlaveRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ChangeReplicationFilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_dumper_ChangeReplicationFilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ChangeReplicationFilterRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ShowSlaveStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_dumper_ShowSlaveStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowSlaveStatusRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_dumper_ShowSlaveStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_dumper_ShowSlaveStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_ShowSlaveStatusResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_dumper_BinlogDumpStatus_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_dumper_BinlogDumpStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_BinlogDumpStatus_descriptor,
        new java.lang.String[] {
            "Ip", "Id", "TraceId", "Port", "FileName", "Position", "Delay", "Bps", "LastSyncTimeStamp",
            "AliveSecond",});
    internal_static_dumper_GetDumperInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_dumper_GetDumperInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dumper_GetDumperInfoResponse_descriptor,
        new java.lang.String[] {
            "File", "Position", "LastEventTimestamp", "Delay", "SessionCount", "AvgDumpBpsSum", "CpuUsage",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
