/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 *
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.aliyun.polardbx.rpc.cdc;

public interface FullBinaryLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dumper.FullBinaryLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string logName = 1;</code>
   * @return The logName.
   */
  java.lang.String getLogName();
  /**
   * <code>string logName = 1;</code>
   * @return The bytes for logName.
   */
  com.google.protobuf.ByteString
      getLogNameBytes();

  /**
   * <code>int64 fileSize = 2;</code>
   * @return The fileSize.
   */
  long getFileSize();

  /**
   * <code>string createdTime = 3;</code>
   * @return The createdTime.
   */
  java.lang.String getCreatedTime();
  /**
   * <code>string createdTime = 3;</code>
   * @return The bytes for createdTime.
   */
  com.google.protobuf.ByteString
      getCreatedTimeBytes();

  /**
   * <code>string lastModifyTime = 4;</code>
   * @return The lastModifyTime.
   */
  java.lang.String getLastModifyTime();
  /**
   * <code>string lastModifyTime = 4;</code>
   * @return The bytes for lastModifyTime.
   */
  com.google.protobuf.ByteString
      getLastModifyTimeBytes();

  /**
   * <code>string firstEventTime = 5;</code>
   * @return The firstEventTime.
   */
  java.lang.String getFirstEventTime();
  /**
   * <code>string firstEventTime = 5;</code>
   * @return The bytes for firstEventTime.
   */
  com.google.protobuf.ByteString
      getFirstEventTimeBytes();

  /**
   * <code>string lastEventTime = 6;</code>
   * @return The lastEventTime.
   */
  java.lang.String getLastEventTime();
  /**
   * <code>string lastEventTime = 6;</code>
   * @return The bytes for lastEventTime.
   */
  com.google.protobuf.ByteString
      getLastEventTimeBytes();

  /**
   * <code>string lastTso = 7;</code>
   * @return The lastTso.
   */
  java.lang.String getLastTso();
  /**
   * <code>string lastTso = 7;</code>
   * @return The bytes for lastTso.
   */
  com.google.protobuf.ByteString
      getLastTsoBytes();

  /**
   * <code>string uploadStatus = 8;</code>
   * @return The uploadStatus.
   */
  java.lang.String getUploadStatus();
  /**
   * <code>string uploadStatus = 8;</code>
   * @return The bytes for uploadStatus.
   */
  com.google.protobuf.ByteString
      getUploadStatusBytes();

  /**
   * <code>string fileLocation = 9;</code>
   * @return The fileLocation.
   */
  java.lang.String getFileLocation();
  /**
   * <code>string fileLocation = 9;</code>
   * @return The bytes for fileLocation.
   */
  com.google.protobuf.ByteString
      getFileLocationBytes();

  /**
   * <code>string ext = 10;</code>
   * @return The ext.
   */
  java.lang.String getExt();
  /**
   * <code>string ext = 10;</code>
   * @return The bytes for ext.
   */
  com.google.protobuf.ByteString
      getExtBytes();
}
