/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 *
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.aliyun.polardbx.rpc.cdc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dumper.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   * @return The req.
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   * @return The bytes for req.
   */
  com.google.protobuf.ByteString
      getReqBytes();

  /**
   * <code>string streamName = 2;</code>
   * @return The streamName.
   */
  java.lang.String getStreamName();
  /**
   * <code>string streamName = 2;</code>
   * @return The bytes for streamName.
   */
  com.google.protobuf.ByteString
      getStreamNameBytes();

  /**
   * <code>bool excludeRemoteFiles = 3;</code>
   * @return The excludeRemoteFiles.
   */
  boolean getExcludeRemoteFiles();
}
