/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 * <p>
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.aliyun.polardbx.rpc.cdc;

public interface ShowBinlogDumpStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dumper.ShowBinlogDumpStatusRequest)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string streamName = 1;</code>
     *
     * @return The streamName.
     */
    java.lang.String getStreamName();

    /**
     * <code>string streamName = 1;</code>
     *
     * @return The bytes for streamName.
     */
    com.google.protobuf.ByteString
    getStreamNameBytes();
}
