/**
 * Copyright (c) 2013-Present, Alibaba Group Holding Limited.
 * All rights reserved.
 * <p>
 * Licensed under the Server Side Public License v1 (SSPLv1).
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DumperServer.proto

package com.aliyun.polardbx.rpc.cdc;

/**
 * Protobuf type {@code dumper.ShowBinlogDumpStatusRequest}
 */
public final class ShowBinlogDumpStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dumper.ShowBinlogDumpStatusRequest)
    ShowBinlogDumpStatusRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ShowBinlogDumpStatusRequest.newBuilder() to construct.
    private ShowBinlogDumpStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ShowBinlogDumpStatusRequest() {
        streamName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
        return new ShowBinlogDumpStatusRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private ShowBinlogDumpStatusRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                case 0:
                    done = true;
                    break;
                case 10: {
                    java.lang.String s = input.readStringRequireUtf8();

                    streamName_ = s;
                    break;
                }
                default: {
                    if (!parseUnknownField(
                        input, unknownFields, extensionRegistry, tag)) {
                        done = true;
                    }
                    break;
                }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.aliyun.polardbx.rpc.cdc.DumperServer.internal_static_dumper_ShowBinlogDumpStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.aliyun.polardbx.rpc.cdc.DumperServer.internal_static_dumper_ShowBinlogDumpStatusRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.class,
                com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.Builder.class);
    }

    public static final int STREAMNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object streamName_;

    /**
     * <code>string streamName = 1;</code>
     *
     * @return The streamName.
     */
    @java.lang.Override
    public java.lang.String getStreamName() {
        java.lang.Object ref = streamName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            streamName_ = s;
            return s;
        }
    }

    /**
     * <code>string streamName = 1;</code>
     *
     * @return The bytes for streamName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getStreamNameBytes() {
        java.lang.Object ref = streamName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            streamName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) {
            return true;
        }
        if (isInitialized == 0) {
            return false;
        }

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!getStreamNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streamName_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) {
            return size;
        }

        size = 0;
        if (!getStreamNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streamName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest)) {
            return super.equals(obj);
        }
        com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest other =
            (com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest) obj;

        if (!getStreamName()
            .equals(other.getStreamName())) {
            return false;
        }
        if (!unknownFields.equals(other.unknownFields)) {
            return false;
        }
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STREAMNAME_FIELD_NUMBER;
        hash = (53 * hash) + getStreamName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code dumper.ShowBinlogDumpStatusRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dumper.ShowBinlogDumpStatusRequest)
        com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.aliyun.polardbx.rpc.cdc.DumperServer.internal_static_dumper_ShowBinlogDumpStatusRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.aliyun.polardbx.rpc.cdc.DumperServer.internal_static_dumper_ShowBinlogDumpStatusRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.class,
                    com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.Builder.class);
        }

        // Construct using com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            streamName_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.aliyun.polardbx.rpc.cdc.DumperServer.internal_static_dumper_ShowBinlogDumpStatusRequest_descriptor;
        }

        @java.lang.Override
        public com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest getDefaultInstanceForType() {
            return com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest build() {
            com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest buildPartial() {
            com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest result =
                new com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest(this);
            result.streamName_ = streamName_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest) {
                return mergeFrom((com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest other) {
            if (other == com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest.getDefaultInstance()) {
                return this;
            }
            if (!other.getStreamName().isEmpty()) {
                streamName_ = other.streamName_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object streamName_ = "";

        /**
         * <code>string streamName = 1;</code>
         *
         * @return The streamName.
         */
        public java.lang.String getStreamName() {
            java.lang.Object ref = streamName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                streamName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string streamName = 1;</code>
         *
         * @return The bytes for streamName.
         */
        public com.google.protobuf.ByteString
        getStreamNameBytes() {
            java.lang.Object ref = streamName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                streamName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string streamName = 1;</code>
         *
         * @param value The streamName to set.
         * @return This builder for chaining.
         */
        public Builder setStreamName(
            java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            streamName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string streamName = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStreamName() {

            streamName_ = getDefaultInstance().getStreamName();
            onChanged();
            return this;
        }

        /**
         * <code>string streamName = 1;</code>
         *
         * @param value The bytes for streamName to set.
         * @return This builder for chaining.
         */
        public Builder setStreamNameBytes(
            com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            streamName_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:dumper.ShowBinlogDumpStatusRequest)
    }

    // @@protoc_insertion_point(class_scope:dumper.ShowBinlogDumpStatusRequest)
    private static final com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest();
    }

    public static com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShowBinlogDumpStatusRequest>
        PARSER = new com.google.protobuf.AbstractParser<ShowBinlogDumpStatusRequest>() {
        @java.lang.Override
        public ShowBinlogDumpStatusRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new ShowBinlogDumpStatusRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<ShowBinlogDumpStatusRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShowBinlogDumpStatusRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.aliyun.polardbx.rpc.cdc.ShowBinlogDumpStatusRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

